### ISSUE TITLE
Harvester error on NYU

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#1192] opened 2024-01-03 14:28 UTC
[Pulmap/production] RSolr::Error::Http: RSolr::Error::Http - 400 Bad RequestError: Document is missing mandatory uniqueKey field: layer_slug_s

## Backtrace

    line 85 of [PROJECT_ROOT]/lib/tasks/pulmap.rake: block (3 levels) in <top (required)>

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54400/faults/102595600)

**Comment by hackartisan** [comment] 2024-01-04 19:18
Same error on BARUCH harvest. See https://app.honeybadger.io/projects/54400/faults/102632503/01HGSPKGWACK5HNNDDXGTZDKB2#notice-summary

**Comment by hackartisan** [comment] 2024-01-05 14:51
This is likely a duplicate of https://github.com/pulibrary/pulmap/issues/1182. When it's done those honeybadger issues should be resolved as well.

**Closed** 2024-01-05 21:23 UTC
Labels: honeybadger, maintenance / research
