### ISSUE TITLE
Fix "Back to Search" style on show page

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pulmap#702] opened 2019-06-24 16:05 UTC
<img width="1179" alt="Screenshot 2019-06-24 11 01 43" src="https://user-images.githubusercontent.com/784196/60034302-f1932780-966f-11e9-8d53-b0bab43c19d3.png">

**Comment by christinach** [comment] 2019-06-24 17:19
duplicate of #677

**Closed** 2019-06-24 17:27 UTC
